### ISSUE TITLE
Snippet code no longer works

### ISSUE THREAD

**Issue by jimtyrro** [impress-org/give-snippet-library#103]
Thank you for a great article but this snippet code no longer working properly.

If I insert into Wordpress via My Custom Functions plugin it crashes the Wordpress site, or if I add it to my functions.php code, it complains about "unexpected < ".

I'd really love to use this code in our donation forms so could you please take a look and see if it's still valid with current version of Wordpress, and why it complains about "unexpected < " in functions.php?

Thank you.

**Comment by DevinWalker** [comment]
The "unexpected <" error seems like an issue conflicting with other code rather than this snippet. As well, I'm not sure which snippet you're talking about. This issues area is meant primarily for development rather than support. If you have a code recommendation or fix please proceed here, otherwise please reach out to us via https://givewp.com/priority-support/

**Comment by jimtyrro** [comment]
Sorry, I forgot to include the reference to the snippet: /form-customizations/populate-amount-name-email-from-url.php

OK, if you're not answering bugs here I will submit a support ticket.
