### ISSUE TITLE
feat: add snippet for moving the custom amount level to the front of the donation levels

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give-snippet-library#94]
# Feature Request

## User Story

As a site admin, I want to move the custom amount level to the front of the list of available donation levels with a custom code snippet so that is the first option my donors see.

## Visuals

![screen_shot_2019-01-07_at_9_31_31_am](https://user-images.githubusercontent.com/20672471/50773678-6a87f980-125f-11e9-9524-ec0cc00547b4.png)

## Possible Solution
Here is where the template is outputting the levels:
https://github.com/impress-org/give/blob/04f56e2db5b6a571a1c5931d910ccb21e2978c20/includes/forms/template.php#L508

Could possibly add an action that would allow the changing of the output order.

## Related

https://secure.helpscout.net/conversation/747438897/32066/

## Acceptance Criteria

- [ ] There is an option for moving the custom amount to the front of the list of available donation level amounts.

**Comment by kevinwhoffman** [comment]
@samsmith89 We discussed this potential snippet on the dev team call and decided we are not going to pursue it since we don't believe the result is a good user experience. Because of the way in which the custom amount control is appended to the other options, there is unfortunately not a preexisting hook that can be leveraged.

Also, web form conventions and left-to-right reading patterns suggest that the custom option should almost always appear last among a set of otherwise predefined options. This way the suggested options are read first, and then the user has the option to choose a custom option if the preset amounts are not suitable. If preset options are not the desired outcome, then perhaps a form with only custom amount enabled is more appropriate than a multi-level form with preset levels.
